version: "3.9"

services:
  backend:
    build: .
    stdin_open: true
    tty: true
    working_dir: /backend
    restart: on-failure
    entrypoint: ["wait-for-it", "database:5432", "--", "python", "manage.py"]
    command: ["runserver", "0.0.0.0:8000"]
    networks:
      - knepp
    volumes:
      - ./backend:/backend/backend:cached
      - internal-media:/backend/internal_media/:cached
    ports:
      - 8000:8000
    depends_on:
      - database
    env_file:
      - envs/local.env
  database:
    image: postgres:13
    ports:
      - 5432:5432
    networks:
      - knepp
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: knepp
      POSTGRES_PASSWORD: knepp
      POSTGRES_DB: knepp

volumes:
  internal-media:
  postgres-data:

networks:
  knepp: